In [1]:
import pandas as pd
df = pd.read_csv('AIDS_REPORTS.csv')
df

c:\users\rickyf~1\desktop\cs506env\env\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (12,14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,AIDS Report Number,Local Event Date,Event City,Event State,Event Airport,Event Type,Aircraft Damage,Flight Phase,Aircraft Make,Aircraft Model,...,Total Injuries,Aircraft Engine Make,Aircraft Engine Model,Engine Group Code,Nbr of Engines,PIC Certificate Type,PIC Flight Time Total Hrs,PIC Flight Time Total Make-Model,,.1
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19780101000019I,1-Jan-78,WAHPETON,ND,BRECKENRIDGE,INCIDENT,MINOR,ROLL-OUT (FIXED WING),CESSNA,CE-182,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,245.0,136.0,0.0,0.0
2,19780101000029I,1-Jan-78,FAIRBANKS,AK,FAIRBANKS INTL,INCIDENT,MINOR,ROLL-OUT (FIXED WING),PIPER,PA-18,...,0.0,NaN,NaN,NaN,1.0,STUDENT,200.0,2.0,0.0,0.0
3,19780101000039I,1-Jan-78,BRUNSWICK,GA,JEKYLL ISLAND,INCIDENT,NaN,NORMAL CRUISE,BEECH,BE-35,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,NaN,0.0,0.0,0.0
4,19780101000049I,1-Jan-78,CARLSBAD,CA,MC CLELLAN-PALOMAR,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-310,...,0.0,NaN,NaN,NaN,2.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,2000.0,400.0,0.0,0.0
5,19780101000059I,1-Jan-78,TROUTDALE,OR,TROUTDALE MUNI,INCIDENT,MINOR,"GROUND TAXI, OTHER AIRPLANE",CESSNA,CE-172,...,0.0,NaN,NaN,NaN,1.0,COMMERCIAL PILOT,300.0,130.0,0.0,0.0
6,19780101000069I,1-Jan-78,HONOLULU,HI,HONOLULU INTL,INCIDENT,NaN,NORMAL CRUISE,BOEING,747,...,0.0,NaN,NaN,NaN,NaN,AIRLINE TRANSPORT,NaN,0.0,0.0,0.0
7,19780101000079I,1-Jan-78,HARRISBURG,PA,HARRISBURG INTL,INCIDENT,NaN,NORMAL CRUISE,MCDONNELL-DOUGLAS-BOEING,DC-9,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,NaN,0.0,0.0,0.0
8,19780101000089I,1-Jan-78,LAFAYETTE,IN,PURDUE UNIVERSITY,INCIDENT,NaN,NORMAL CRUISE,PIPER,PA-31,...,0.0,NaN,NaN,NaN,2.0,COMMERCIAL PILOT,2700.0,75.0,0.0,0.0
9,19780101000099I,1-Jan-78,ANCHORAGE,AK,TED STEVENS ANCHORAGE INTL,INCIDENT,NaN,DESCENT,CESSNA,CE-150,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,450.0,430.0,0.0,0.0
10,19780102000339I,2-Jan-78,CRYSTAL RIVER,FL,NaN,INCIDENT,MINOR,ROLL-OUT (FIXED WING),CESSNA,CE-172,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,90.0,45.0,0.0,0.0
11,19780102000359I,2-Jan-78,LANGDON,ND,LANGDON MUNI,INCIDENT,MINOR,TOUCH AND GO LANDING,GULSTM,GA-AA,...,0.0,NaN,NaN,NaN,1.0,STUDENT,29.0,21.0,0.0,0.0
12,19780102000369I,2-Jan-78,WHEELING,IL,CHICAGO EXECUTIVE,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,PIPER,PA-30,...,0.0,NaN,NaN,NaN,2.0,PRIVATE PILOT,2300.0,500.0,0.0,0.0
13,19780102000399I,2-Jan-78,RAEFORD,NC,RAEFORD MUNI,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,PIPER,PA-24,...,0.0,NaN,NaN,NaN,1.0,COMMERCIAL PILOT,2300.0,125.0,0.0,0.0
14,19780102000409I,2-Jan-78,MIDLAND,TX,MIDLAND INTL,INCIDENT,MINOR,"GROUND TAXI, OTHER AIRPLANE",PIPER,PA-28,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,100.0,50.0,0.0,0.0
15,19780102000429I,2-Jan-78,ARNETT,OK,ARNETT MUNI,INCIDENT,MINOR,TO ABORTED (FIXED WING),PIPER,PA-28,...,0.0,NaN,NaN,NaN,NaN,PRIVATE PILOT,120.0,25.0,0.0,0.0
16,19780102000439I,2-Jan-78,INDIANOLA,IA,NaN,INCIDENT,NaN,FCD/PREC LDG FROM CRUISE,PIPER,PA-32,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,565.0,275.0,0.0,0.0
17,19780102000459I,2-Jan-78,SANTEE,CA,GILLESPIE FIELD,INCIDENT,MINOR,"GROUND TAXI, OTHER AIRPLANE",PIPER,PA-28,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,115.0,103.0,0.0,0.0
18,19780102000479I,2-Jan-78,DERBY,KS,COOK AIRFIELD INC,INCIDENT,SUBSTANTIAL,FORCED LANDING,CESSNA,CE-210,...,0.0,CONT,IO470E,O470,1.0,COMMERCIAL PILOT,865.0,8.0,0.0,0.0
19,19780102000499I,2-Jan-78,SANTEE,CA,GILLESPIE FIELD,INCIDENT,MINOR,ROLL-OUT (FIXED WING),PIPER,PA-18,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,200.0,170.0,0.0,0.0
20,19780102000509I,2-Jan-78,WATERTOWN,WI,WATERTOWN MUNI,INCIDENT,MINOR,ENGINE RUN-UP,CESSNA,CE-195,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,NaN,0.0,0.0,0.0
21,19780102000519I,2-Jan-78,MINOT,ND,NaN,INCIDENT,NaN,FCD/PREC LDG FROM CRUISE,CESSNA,CE-150,...,0.0,CONT,O200A,O200,1.0,PRIVATE PILOT,600.0,100.0,0.0,0.0
22,19780102000529I,2-Jan-78,SPRINGFIELD,MO,SPRINGFIELD MUNI,INCIDENT,NaN,TAKEOFF GROUND ROLL,MARTIN,M-404,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,NaN,0.0,0.0,0.0
23,19780102000539I,2-Jan-78,DALLAS,TX,MIDLAND INTL,INCIDENT,NaN,CLIMB,MCDONNELL-DOUGLAS-BOEING,DC-9,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,NaN,0.0,0.0,0.0
24,19780102000559I,2-Jan-78,NaN,NaN,SAN ANDROS MUNI,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-401,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,4400.0,280.0,0.0,0.0
25,19780102000569I,2-Jan-78,SUFFOLK,VA,SUFFOLK EXECUTIVE,INCIDENT,NaN,DESCENT,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,COMMERCIAL PILOT,NaN,0.0,0.0,0.0
26,19780103000669I,3-Jan-78,ANCHORAGE,AK,TED STEVENS ANCHORAGE INTL,INCIDENT,NaN,NORMAL CRUISE,CESSNA,CE-402,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,2800.0,150.0,0.0,0.0
27,19780103000689I,3-Jan-78,HARLAN,IA,HARLAN MUNI,INCIDENT,MINOR,CLIMB,CESSNA,CE-177,...,0.0,NaN,NaN,NaN,1.0,COMMERCIAL PILOT,1900.0,1500.0,0.0,0.0
28,19780103000719I,3-Jan-78,CAMERON,LA,NaN,INCIDENT,NaN,FCD/PREC LDG FROM CRUISE,BELL,BHT-206,...,0.0,ALLSN,250C20B,250C,1.0,COMMERCIAL PILOT,3650.0,1564.0,0.0,0.0
29,19780103000739I,3-Jan-78,AMARILLO,TX,RICK HUSBAND AMARILLO INTL,INCIDENT,NaN,CLIMB,MITSUBISHI,MU-2B,...,0.0,NaN,NaN,NaN,2.0,COMMERCIAL PILOT,2400.0,2200.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,20151205020629I,5-Dec-15,ODESSA,TX,ODESSA-SCHLEMEYER FIELD,INCIDENT,SUBSTANTIAL,LANDING: TOUCHDOWN,CESSNA,CE-310,...,0.0,CONT M,O-470 SERIES,NaN,2.0,COMMERCIAL PILOT,5900.0,26.0,50.0,NaN
99971,20151205024179I,5-Dec-15,ANCHORAGE,AK,TED STEVENS ANCHORAGE INTL,INCIDENT,MINOR,TAXI,BOEING,747,...,0.0,NaN,NaN,NaN,NaN,UNKNOWN/FOREIGN,NaN,NaN,NaN,NaN
99972,20151206020239I,6-Dec-15,NORTH KINGSTOWN,RI,QUONSET STATE,INCIDENT,MINOR,GROUND-RAMP,BEECH,BE-36,...,0.0,CONT M,IO-550 SERIES,B,1.0,PRIVATE PILOT,1628.0,880.0,24.0,NaN
99973,20151206021209I,6-Dec-15,CHINO,CA,CHINO,INCIDENT,NONE,CRUISE-LEVEL FLIGHT,BEECH,BE-76,...,0.0,LYCOMI,O&VO-360 SER,NaN,2.0,AIRLINE TRANSPORT,15050.0,750.0,100.0,NaN
99974,20151206021219I,6-Dec-15,RIVERSIDE,CA,RIVERSIDE MUNI,INCIDENT,NONE,CRUISE-LEVEL FLIGHT,BEECH,BE-76,...,0.0,LYCOMI,O&VO-360 SER,NaN,2.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,3357.0,110.0,15.0,NaN
99975,20151206022929I,6-Dec-15,ROME,NY,NaN,INCIDENT,MINOR,LANDING: ROLLOUT,NaN,NaN,...,0.0,LYCOMI,IO-540 SER,NaN,NaN,PRIVATE PILOT,1903.0,40.0,1.0,NaN
99976,20151207019439I,7-Dec-15,ADDISON,TX,ADDISON,INCIDENT,MINOR,TAXI,CESSNA,CE-172,...,0.0,LYCOMI,I0360 SER A&C,NaN,1.0,PRIVATE PILOT FLIGHT INSTRUCTOR,880.0,400.0,200.0,NaN
99977,20151207020019I,7-Dec-15,OAKES,ND,OAKES MUNI,INCIDENT,MINOR,CRUISE-LEVEL FLIGHT,MOONEY,M-20,...,0.0,LYCOMI,I0360 SER A&C,NaN,1.0,NaN,NaN,NaN,NaN,NaN
99978,20151207022909I,7-Dec-15,SITKA,AK,SITKA ROCKY GUTIERREZ,INCIDENT,MINOR,LANDING: TOUCHDOWN,CESSNA,CE-185,...,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
99979,20151208019799I,8-Dec-15,CEDAR CITY,UT,CEDAR CITY RGNL,INCIDENT,MINOR,LANDING: TOUCHDOWN,TECNAM,NaN,...,0.0,ROTAX,912S3,NaN,2.0,PRIVATE PILOT,258.0,129.0,24.0,NaN
99980,20151208021499I,8-Dec-15,SANTA YNEZ,CA,SANTA YNEZ,INCIDENT,MINOR,LANDING: ROLLOUT,BEECH,BE-33,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,285.0,198.0,68.0,NaN
99981,20151208024119I,8-Dec-15,SEAL BEACH,CA,NaN,INCIDENT,MINOR,CRUISE-LEVEL FLIGHT,LANCAIR,LC-41,...,0.0,CONT M,TSIO-550-C,550,NaN,PRIVATE PILOT FLIGHT INSTRUCTOR,4490.0,NaN,NaN,NaN
99982,20151209020459I,9-Dec-15,FORT LAUDERDALE,FL,FORT LAUDERDALE EXECUTIVE,INCIDENT,SUBSTANTIAL,LANDING: ROLLOUT,CESSNA,CE-172,...,0.0,LYCOMI,I0360 SER A&C,NaN,1.0,UNKNOWN/FOREIGN,NaN,NaN,5.0,NaN
99983,20151209020469I,9-Dec-15,WEST PALM BEACH,FL,NORTH PALM BEACH COUNTY GENERAL AVIATION,INCIDENT,MINOR,HOVER-HOLDING,ROBSIN,R-44,...,0.0,LYCOMI,0-540F1 SERIE,NaN,1.0,PRIVATE PILOT,80.0,26.0,26.0,NaN
99984,20151211019629I,11-Dec-15,HASKELL,TX,HASKELL MUNI,INCIDENT,MINOR,LANDING: TOUCHDOWN,CESSNA,CE-210,...,0.0,CONT M,IO 520 SERIES,NaN,1.0,AIRLINE TRANSPORT,NaN,78.0,NaN,NaN
99985,20151212019219I,12-Dec-15,BLAIRSTOWN,NJ,BLAIRSTOWN,INCIDENT,MINOR,LANDING: TOUCHDOWN,NAVION,NAV-1,...,0.0,CONT M,IO-520-BB,NaN,1.0,PRIVATE PILOT,1474.0,400.0,21.0,NaN
99986,20151212021359I,12-Dec-15,WESTFIELD,MA,BARNES MUNI,INCIDENT,MINOR,TAKEOFF: DEPARTURE,EXTRA,EXTRA-EA,...,0.0,LYCOMI,AEIO-540 SER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99987,20151212022479I,12-Dec-15,SANTA ROSA,CA,CHARLES M. SCHULZ - SONOMA COUNTY,INCIDENT,SUBSTANTIAL,LANDING: TOUCHDOWN,BEECH,BE-35,...,0.0,CONT M,I0-470 SERIES,NaN,1.0,COMMERCIAL PILOT,960.0,717.0,36.0,NaN
99988,20151213020069I,13-Dec-15,BATAVIA,OH,CLERMONT COUNTY,INCIDENT,MINOR,LANDING: APPROACH,CESSNA,CE-310,...,0.0,CONT M,I0-470-VO,CONT I,2.0,PRIVATE PILOT,2398.0,863.0,38.0,NaN
99989,20151214023289I,14-Dec-15,PORT MANSFIELD,TX,CHARLES R JOHNSON,INCIDENT,MINOR,LANDING: TOUCHDOWN,AVIAT,AVIAT-A,...,0.0,LYCOMI,0-320 SERIES,NaN,NaN,PRIVATE PILOT,935.0,34.0,39.0,NaN
99990,20151215018779I,15-Dec-15,SPOKANE,WA,SPOKANE INTL,INCIDENT,NONE,DESCENT,DE HAVILLAND-BOMBARDIER,DASH 8,...,0.0,P&W CA,PW150A,PW150A,NaN,NaN,NaN,NaN,NaN,NaN
99991,20151215019559I,15-Dec-15,LAKE CHARLES,LA,CHENNAULT INTL,INCIDENT,MINOR,TAKEOFF: DEPARTURE,NaN,NaN,...,0.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
99992,20151215022429I,15-Dec-15,SAN LUIS OBISPO,CA,SAN LUIS COUNTY RGNL,INCIDENT,MINOR,LANDING: APPROACH,CESSNA,CE-210,...,0.0,CONT M,IO 520 SERIES,NaN,1.0,NaN,NaN,NaN,NaN,NaN
99993,20151215023509I,15-Dec-15,CHESAPEAKE,VA,HAMPTON ROADS EXECUTIVE,INCIDENT,MINOR,LANDING: TOUCHDOWN,CESSNA,CE-172,...,0.0,LYCOMI,O&VO-360 SER,360,1.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,2200.0,15.0,106.0,NaN
99994,20151216019599I,16-Dec-15,KALAMAZOO,MI,KALAMAZOO/BATTLE CREEK INTL,INCIDENT,SUBSTANTIAL,LANDING: TOUCHDOWN,BEECH,BE-36,...,0.0,CONT M,IO-550 SERIES,NaN,1.0,NaN,NaN,NaN,NaN,NaN
99995,20151217022219I,17-Dec-15,VENICE,FL,VENICE MUNI,INCIDENT,MINOR,LANDING: ROLLOUT,PARKS,NaN,...,0.0,AMA/EX,UNKNOWN ENG,NaN,NaN,AIRLINE TRANSPORT,16650.0,NaN,NaN,NaN
99996,20151217023139I,17-Dec-15,PHOENIX,AZ,PHOENIX SKY HARBOR INTL,INCIDENT,MINOR,TAKEOFF: CLIMB OUT,RAYTHEON,RA-390,...,0.0,WILLIA,FJ44-2A,TURBOF,2.0,AIRLINE TRANSPORT PILOT FLIGHT INSTRUCTOR,NaN,230.0,NaN,NaN
99997,20151218021509I,18-Dec-15,NaN,NaN,CAMARILLO,INCIDENT,MINOR,LANDING: APPROACH,CESSNA,CITATION 550 II,...,0.0,P&W CA,PW530A,NaN,2.0,UNKNOWN/FOREIGN,5500.0,150.0,NaN,NaN
99998,20151218021729I,18-Dec-15,BELLEVILLE,MI,WILLOW RUN,INCIDENT,MINOR,MANEUVER,CESSNA,CE-172,...,0.0,LYCOMI,O&VO-360 SER,NaN,1.0,PRIVATE PILOT,267.0,44.0,20.0,NaN
99999,20151218024079I,18-Dec-15,LEAVENWORTH,KS,SHERMAN AAF,INCIDENT,MINOR,LANDING: TOUCHDOWN,PIPER,PA-28,...,0.0,LYCOMI,O&VO-360 SER,NaN,NaN,STUDENT,18.0,13.0,13.0,NaN

In [2]:
df2 = pd.read_csv('PEP_2017_PEPCUMCHG.ST05_with_ann_sorted_small.csv')
df2

,Id2,Geography,"Population Estimate - April 1, 2010 Estimates Base","Population Estimate - July 1, 2017"
0,1,Alabama,4780135,4874747
1,2,Alaska,710249,739795
2,4,Arizona,6392309,7016270
3,5,Arkansas,2916031,3004279
4,6,California,37254518,39536653
5,8,Colorado,5029325,5607154
6,9,Connecticut,3574114,3588184
7,10,Delaware,897936,961939
8,11,District of Columbia,601766,693972
9,12,Florida,18804594,20984400
10,13,Georgia,9688690,10429379
11,15,Hawaii,1360301,1427538
12,16,Idaho,1567650,1716943
13,17,Illinois,12831565,12802023
14,18,Indiana,6484125,6666818
15,19,Iowa,3046869,3145711
16,20,Kansas,2853130,2913123
17,21,Kentucky,4339340,4454189
18,22,Louisiana,4533478,4684333
19,23,Maine,1328362,1335907
20,24,Maryland,5773807,6052177
21,25,Massachusetts,6547808,6859819
22,26,Michigan,9884129,9962311
23,27,Minnesota,5303924,5576606
24,28,Mississippi,2968103,2984100
25,29,Missouri,5988925,6113532
26,30,Montana,989414,1050493
27,31,Nebraska,1826327,1920076
28,32,Nevada,2700691,2998039
29,33,New Hampshire,1316460,1342795
30,34,New Jersey,8791953,9005644
31,35,New Mexico,2059207,2088070
32,36,New York,19378110,19849399
33,37,North Carolina,9535721,10273419
34,38,North Dakota,672585,755393
35,39,Ohio,11536730,11658609
36,40,Oklahoma,3751598,3930864
37,41,Oregon,3831072,4142776
38,42,Pennsylvania,12702857,12805537
39,44,Rhode Island,1052945,1059639
40,45,South Carolina,4625381,5024369
41,46,South Dakota,814197,869666
42,47,Tennessee,6346295,6715984
43,48,Texas,25146100,28304596
44,49,Utah,2763889,3101833
45,50,Vermont,625741,623657
46,51,Virginia,8001043,8470020
47,53,Washington,6724545,7405743
48,54,West Virginia,1853006,1815857
49,55,Wisconsin,5687288,5795483
50,56,Wyoming,563767,579315
51,72,Puerto Rico,3726157,3337177

In [3]:
len(df2['Geography'].value_counts())

52

In [4]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

In [5]:
df3 = pd.DataFrame.from_dict(us_state_abbrev, orient='index')
df3

                 0
Alabama         AL
Alaska          AK
Arizona         AZ
Arkansas        AR
California      CA
Colorado        CO
Connecticut     CT
Delaware        DE
Florida         FL
Georgia         GA
Hawaii          HI
Idaho           ID
Illinois        IL
Indiana         IN
Iowa            IA
Kansas          KS
Kentucky        KY
Louisiana       LA
Maine           ME
Maryland        MD
Massachusetts   MA
Michigan        MI
Minnesota       MN
Mississippi     MS
Missouri        MO
Montana         MT
Nebraska        NE
Nevada          NV
New Hampshire   NH
New Jersey      NJ
New Mexico      NM
New York        NY
North Carolina  NC
North Dakota    ND
Ohio            OH
Oklahoma        OK
Oregon          OR
Pennsylvania    PA
Rhode Island    RI
South Carolina  SC
South Dakota    SD
Tennessee       TN
Texas           TX
Utah            UT
Vermont         VT
Virginia        VA
Washington      WA
West Virginia   WV
Wisconsin       WI
Wyoming         WY

In [6]:
df2_abrv = df2.join(df3, on='Geography')

In [7]:
# Now have a df containing the state abreviations and the population estimates
df2_abrv

# need to join this with the original dataset, and then normalize state counts based on their population

,Id2,Geography,"Population Estimate - April 1, 2010 Estimates Base","Population Estimate - July 1, 2017",0
0,1,Alabama,4780135,4874747,AL
1,2,Alaska,710249,739795,AK
2,4,Arizona,6392309,7016270,AZ
3,5,Arkansas,2916031,3004279,AR
4,6,California,37254518,39536653,CA
5,8,Colorado,5029325,5607154,CO
6,9,Connecticut,3574114,3588184,CT
7,10,Delaware,897936,961939,DE
8,11,District of Columbia,601766,693972,NaN
9,12,Florida,18804594,20984400,FL
10,13,Georgia,9688690,10429379,GA
11,15,Hawaii,1360301,1427538,HI
12,16,Idaho,1567650,1716943,ID
13,17,Illinois,12831565,12802023,IL
14,18,Indiana,6484125,6666818,IN
15,19,Iowa,3046869,3145711,IA
16,20,Kansas,2853130,2913123,KS
17,21,Kentucky,4339340,4454189,KY
18,22,Louisiana,4533478,4684333,LA
19,23,Maine,1328362,1335907,ME
20,24,Maryland,5773807,6052177,MD
21,25,Massachusetts,6547808,6859819,MA
22,26,Michigan,9884129,9962311,MI
23,27,Minnesota,5303924,5576606,MN
24,28,Mississippi,2968103,2984100,MS
25,29,Missouri,5988925,6113532,MO
26,30,Montana,989414,1050493,MT
27,31,Nebraska,1826327,1920076,NE
28,32,Nevada,2700691,2998039,NV
29,33,New Hampshire,1316460,1342795,NH
30,34,New Jersey,8791953,9005644,NJ
31,35,New Mexico,2059207,2088070,NM
32,36,New York,19378110,19849399,NY
33,37,North Carolina,9535721,10273419,NC
34,38,North Dakota,672585,755393,ND
35,39,Ohio,11536730,11658609,OH
36,40,Oklahoma,3751598,3930864,OK
37,41,Oregon,3831072,4142776,OR
38,42,Pennsylvania,12702857,12805537,PA
39,44,Rhode Island,1052945,1059639,RI
40,45,South Carolina,4625381,5024369,SC
41,46,South Dakota,814197,869666,SD
42,47,Tennessee,6346295,6715984,TN
43,48,Texas,25146100,28304596,TX
44,49,Utah,2763889,3101833,UT
45,50,Vermont,625741,623657,VT
46,51,Virginia,8001043,8470020,VA
47,53,Washington,6724545,7405743,WA
48,54,West Virginia,1853006,1815857,WV
49,55,Wisconsin,5687288,5795483,WI
50,56,Wyoming,563767,579315,WY
51,72,Puerto Rico,3726157,3337177,NaN