In [1]:
# Code for creating the normalized version of the accidents per state plot
import pandas as pd
df = pd.read_csv('AIDS_REPORTS.csv')
df

c:\users\rickyf~1\desktop\cs506env\env\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (12,14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,AIDS Report Number,Local Event Date,Event City,Event State,Event Airport,Event Type,Aircraft Damage,Flight Phase,Aircraft Make,Aircraft Model,...,Total Injuries,Aircraft Engine Make,Aircraft Engine Model,Engine Group Code,Nbr of Engines,PIC Certificate Type,PIC Flight Time Total Hrs,PIC Flight Time Total Make-Model,,.1
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19780101000019I,1-Jan-78,WAHPETON,ND,BRECKENRIDGE,INCIDENT,MINOR,ROLL-OUT (FIXED WING),CESSNA,CE-182,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,245.0,136.0,0.0,0.0
2,19780101000029I,1-Jan-78,FAIRBANKS,AK,FAIRBANKS INTL,INCIDENT,MINOR,ROLL-OUT (FIXED WING),PIPER,PA-18,...,0.0,NaN,NaN,NaN,1.0,STUDENT,200.0,2.0,0.0,0.0
3,19780101000039I,1-Jan-78,BRUNSWICK,GA,JEKYLL ISLAND,INCIDENT,NaN,NORMAL CRUISE,BEECH,BE-35,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,NaN,0.0,0.0,0.0
4,19780101000049I,1-Jan-78,CARLSBAD,CA,MC CLELLAN-PALOMAR,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-310,...,0.0,NaN,NaN,NaN,2.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,2000.0,400.0,0.0,0.0
5,19780101000059I,1-Jan-78,TROUTDALE,OR,TROUTDALE MUNI,INCIDENT,MINOR,"GROUND TAXI, OTHER AIRPLANE",CESSNA,CE-172,...,0.0,NaN,NaN,NaN,1.0,COMMERCIAL PILOT,300.0,130.0,0.0,0.0
6,19780101000069I,1-Jan-78,HONOLULU,HI,HONOLULU INTL,INCIDENT,NaN,NORMAL CRUISE,BOEING,747,...,0.0,NaN,NaN,NaN,NaN,AIRLINE TRANSPORT,NaN,0.0,0.0,0.0
7,19780101000079I,1-Jan-78,HARRISBURG,PA,HARRISBURG INTL,INCIDENT,NaN,NORMAL CRUISE,MCDONNELL-DOUGLAS-BOEING,DC-9,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,NaN,0.0,0.0,0.0
8,19780101000089I,1-Jan-78,LAFAYETTE,IN,PURDUE UNIVERSITY,INCIDENT,NaN,NORMAL CRUISE,PIPER,PA-31,...,0.0,NaN,NaN,NaN,2.0,COMMERCIAL PILOT,2700.0,75.0,0.0,0.0
9,19780101000099I,1-Jan-78,ANCHORAGE,AK,TED STEVENS ANCHORAGE INTL,INCIDENT,NaN,DESCENT,CESSNA,CE-150,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,450.0,430.0,0.0,0.0
10,19780102000339I,2-Jan-78,CRYSTAL RIVER,FL,NaN,INCIDENT,MINOR,ROLL-OUT (FIXED WING),CESSNA,CE-172,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,90.0,45.0,0.0,0.0
11,19780102000359I,2-Jan-78,LANGDON,ND,LANGDON MUNI,INCIDENT,MINOR,TOUCH AND GO LANDING,GULSTM,GA-AA,...,0.0,NaN,NaN,NaN,1.0,STUDENT,29.0,21.0,0.0,0.0
12,19780102000369I,2-Jan-78,WHEELING,IL,CHICAGO EXECUTIVE,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,PIPER,PA-30,...,0.0,NaN,NaN,NaN,2.0,PRIVATE PILOT,2300.0,500.0,0.0,0.0
13,19780102000399I,2-Jan-78,RAEFORD,NC,RAEFORD MUNI,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,PIPER,PA-24,...,0.0,NaN,NaN,NaN,1.0,COMMERCIAL PILOT,2300.0,125.0,0.0,0.0
14,19780102000409I,2-Jan-78,MIDLAND,TX,MIDLAND INTL,INCIDENT,MINOR,"GROUND TAXI, OTHER AIRPLANE",PIPER,PA-28,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,100.0,50.0,0.0,0.0
15,19780102000429I,2-Jan-78,ARNETT,OK,ARNETT MUNI,INCIDENT,MINOR,TO ABORTED (FIXED WING),PIPER,PA-28,...,0.0,NaN,NaN,NaN,NaN,PRIVATE PILOT,120.0,25.0,0.0,0.0
16,19780102000439I,2-Jan-78,INDIANOLA,IA,NaN,INCIDENT,NaN,FCD/PREC LDG FROM CRUISE,PIPER,PA-32,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,565.0,275.0,0.0,0.0
17,19780102000459I,2-Jan-78,SANTEE,CA,GILLESPIE FIELD,INCIDENT,MINOR,"GROUND TAXI, OTHER AIRPLANE",PIPER,PA-28,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,115.0,103.0,0.0,0.0
18,19780102000479I,2-Jan-78,DERBY,KS,COOK AIRFIELD INC,INCIDENT,SUBSTANTIAL,FORCED LANDING,CESSNA,CE-210,...,0.0,CONT,IO470E,O470,1.0,COMMERCIAL PILOT,865.0,8.0,0.0,0.0
19,19780102000499I,2-Jan-78,SANTEE,CA,GILLESPIE FIELD,INCIDENT,MINOR,ROLL-OUT (FIXED WING),PIPER,PA-18,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,200.0,170.0,0.0,0.0
20,19780102000509I,2-Jan-78,WATERTOWN,WI,WATERTOWN MUNI,INCIDENT,MINOR,ENGINE RUN-UP,CESSNA,CE-195,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,NaN,0.0,0.0,0.0
21,19780102000519I,2-Jan-78,MINOT,ND,NaN,INCIDENT,NaN,FCD/PREC LDG FROM CRUISE,CESSNA,CE-150,...,0.0,CONT,O200A,O200,1.0,PRIVATE PILOT,600.0,100.0,0.0,0.0
22,19780102000529I,2-Jan-78,SPRINGFIELD,MO,SPRINGFIELD MUNI,INCIDENT,NaN,TAKEOFF GROUND ROLL,MARTIN,M-404,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,NaN,0.0,0.0,0.0
23,19780102000539I,2-Jan-78,DALLAS,TX,MIDLAND INTL,INCIDENT,NaN,CLIMB,MCDONNELL-DOUGLAS-BOEING,DC-9,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,NaN,0.0,0.0,0.0
24,19780102000559I,2-Jan-78,NaN,NaN,SAN ANDROS MUNI,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-401,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,4400.0,280.0,0.0,0.0
25,19780102000569I,2-Jan-78,SUFFOLK,VA,SUFFOLK EXECUTIVE,INCIDENT,NaN,DESCENT,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,COMMERCIAL PILOT,NaN,0.0,0.0,0.0
26,19780103000669I,3-Jan-78,ANCHORAGE,AK,TED STEVENS ANCHORAGE INTL,INCIDENT,NaN,NORMAL CRUISE,CESSNA,CE-402,...,0.0,NaN,NaN,NaN,2.0,AIRLINE TRANSPORT,2800.0,150.0,0.0,0.0
27,19780103000689I,3-Jan-78,HARLAN,IA,HARLAN MUNI,INCIDENT,MINOR,CLIMB,CESSNA,CE-177,...,0.0,NaN,NaN,NaN,1.0,COMMERCIAL PILOT,1900.0,1500.0,0.0,0.0
28,19780103000719I,3-Jan-78,CAMERON,LA,NaN,INCIDENT,NaN,FCD/PREC LDG FROM CRUISE,BELL,BHT-206,...,0.0,ALLSN,250C20B,250C,1.0,COMMERCIAL PILOT,3650.0,1564.0,0.0,0.0
29,19780103000739I,3-Jan-78,AMARILLO,TX,RICK HUSBAND AMARILLO INTL,INCIDENT,NaN,CLIMB,MITSUBISHI,MU-2B,...,0.0,NaN,NaN,NaN,2.0,COMMERCIAL PILOT,2400.0,2200.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,20151205020629I,5-Dec-15,ODESSA,TX,ODESSA-SCHLEMEYER FIELD,INCIDENT,SUBSTANTIAL,LANDING: TOUCHDOWN,CESSNA,CE-310,...,0.0,CONT M,O-470 SERIES,NaN,2.0,COMMERCIAL PILOT,5900.0,26.0,50.0,NaN
99971,20151205024179I,5-Dec-15,ANCHORAGE,AK,TED STEVENS ANCHORAGE INTL,INCIDENT,MINOR,TAXI,BOEING,747,...,0.0,NaN,NaN,NaN,NaN,UNKNOWN/FOREIGN,NaN,NaN,NaN,NaN
99972,20151206020239I,6-Dec-15,NORTH KINGSTOWN,RI,QUONSET STATE,INCIDENT,MINOR,GROUND-RAMP,BEECH,BE-36,...,0.0,CONT M,IO-550 SERIES,B,1.0,PRIVATE PILOT,1628.0,880.0,24.0,NaN
99973,20151206021209I,6-Dec-15,CHINO,CA,CHINO,INCIDENT,NONE,CRUISE-LEVEL FLIGHT,BEECH,BE-76,...,0.0,LYCOMI,O&VO-360 SER,NaN,2.0,AIRLINE TRANSPORT,15050.0,750.0,100.0,NaN
99974,20151206021219I,6-Dec-15,RIVERSIDE,CA,RIVERSIDE MUNI,INCIDENT,NONE,CRUISE-LEVEL FLIGHT,BEECH,BE-76,...,0.0,LYCOMI,O&VO-360 SER,NaN,2.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,3357.0,110.0,15.0,NaN
99975,20151206022929I,6-Dec-15,ROME,NY,NaN,INCIDENT,MINOR,LANDING: ROLLOUT,NaN,NaN,...,0.0,LYCOMI,IO-540 SER,NaN,NaN,PRIVATE PILOT,1903.0,40.0,1.0,NaN
99976,20151207019439I,7-Dec-15,ADDISON,TX,ADDISON,INCIDENT,MINOR,TAXI,CESSNA,CE-172,...,0.0,LYCOMI,I0360 SER A&C,NaN,1.0,PRIVATE PILOT FLIGHT INSTRUCTOR,880.0,400.0,200.0,NaN
99977,20151207020019I,7-Dec-15,OAKES,ND,OAKES MUNI,INCIDENT,MINOR,CRUISE-LEVEL FLIGHT,MOONEY,M-20,...,0.0,LYCOMI,I0360 SER A&C,NaN,1.0,NaN,NaN,NaN,NaN,NaN
99978,20151207022909I,7-Dec-15,SITKA,AK,SITKA ROCKY GUTIERREZ,INCIDENT,MINOR,LANDING: TOUCHDOWN,CESSNA,CE-185,...,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
99979,20151208019799I,8-Dec-15,CEDAR CITY,UT,CEDAR CITY RGNL,INCIDENT,MINOR,LANDING: TOUCHDOWN,TECNAM,NaN,...,0.0,ROTAX,912S3,NaN,2.0,PRIVATE PILOT,258.0,129.0,24.0,NaN
99980,20151208021499I,8-Dec-15,SANTA YNEZ,CA,SANTA YNEZ,INCIDENT,MINOR,LANDING: ROLLOUT,BEECH,BE-33,...,0.0,NaN,NaN,NaN,1.0,PRIVATE PILOT,285.0,198.0,68.0,NaN
99981,20151208024119I,8-Dec-15,SEAL BEACH,CA,NaN,INCIDENT,MINOR,CRUISE-LEVEL FLIGHT,LANCAIR,LC-41,...,0.0,CONT M,TSIO-550-C,550,NaN,PRIVATE PILOT FLIGHT INSTRUCTOR,4490.0,NaN,NaN,NaN
99982,20151209020459I,9-Dec-15,FORT LAUDERDALE,FL,FORT LAUDERDALE EXECUTIVE,INCIDENT,SUBSTANTIAL,LANDING: ROLLOUT,CESSNA,CE-172,...,0.0,LYCOMI,I0360 SER A&C,NaN,1.0,UNKNOWN/FOREIGN,NaN,NaN,5.0,NaN
99983,20151209020469I,9-Dec-15,WEST PALM BEACH,FL,NORTH PALM BEACH COUNTY GENERAL AVIATION,INCIDENT,MINOR,HOVER-HOLDING,ROBSIN,R-44,...,0.0,LYCOMI,0-540F1 SERIE,NaN,1.0,PRIVATE PILOT,80.0,26.0,26.0,NaN
99984,20151211019629I,11-Dec-15,HASKELL,TX,HASKELL MUNI,INCIDENT,MINOR,LANDING: TOUCHDOWN,CESSNA,CE-210,...,0.0,CONT M,IO 520 SERIES,NaN,1.0,AIRLINE TRANSPORT,NaN,78.0,NaN,NaN
99985,20151212019219I,12-Dec-15,BLAIRSTOWN,NJ,BLAIRSTOWN,INCIDENT,MINOR,LANDING: TOUCHDOWN,NAVION,NAV-1,...,0.0,CONT M,IO-520-BB,NaN,1.0,PRIVATE PILOT,1474.0,400.0,21.0,NaN
99986,20151212021359I,12-Dec-15,WESTFIELD,MA,BARNES MUNI,INCIDENT,MINOR,TAKEOFF: DEPARTURE,EXTRA,EXTRA-EA,...,0.0,LYCOMI,AEIO-540 SER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99987,20151212022479I,12-Dec-15,SANTA ROSA,CA,CHARLES M. SCHULZ - SONOMA COUNTY,INCIDENT,SUBSTANTIAL,LANDING: TOUCHDOWN,BEECH,BE-35,...,0.0,CONT M,I0-470 SERIES,NaN,1.0,COMMERCIAL PILOT,960.0,717.0,36.0,NaN
99988,20151213020069I,13-Dec-15,BATAVIA,OH,CLERMONT COUNTY,INCIDENT,MINOR,LANDING: APPROACH,CESSNA,CE-310,...,0.0,CONT M,I0-470-VO,CONT I,2.0,PRIVATE PILOT,2398.0,863.0,38.0,NaN
99989,20151214023289I,14-Dec-15,PORT MANSFIELD,TX,CHARLES R JOHNSON,INCIDENT,MINOR,LANDING: TOUCHDOWN,AVIAT,AVIAT-A,...,0.0,LYCOMI,0-320 SERIES,NaN,NaN,PRIVATE PILOT,935.0,34.0,39.0,NaN
99990,20151215018779I,15-Dec-15,SPOKANE,WA,SPOKANE INTL,INCIDENT,NONE,DESCENT,DE HAVILLAND-BOMBARDIER,DASH 8,...,0.0,P&W CA,PW150A,PW150A,NaN,NaN,NaN,NaN,NaN,NaN
99991,20151215019559I,15-Dec-15,LAKE CHARLES,LA,CHENNAULT INTL,INCIDENT,MINOR,TAKEOFF: DEPARTURE,NaN,NaN,...,0.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
99992,20151215022429I,15-Dec-15,SAN LUIS OBISPO,CA,SAN LUIS COUNTY RGNL,INCIDENT,MINOR,LANDING: APPROACH,CESSNA,CE-210,...,0.0,CONT M,IO 520 SERIES,NaN,1.0,NaN,NaN,NaN,NaN,NaN
99993,20151215023509I,15-Dec-15,CHESAPEAKE,VA,HAMPTON ROADS EXECUTIVE,INCIDENT,MINOR,LANDING: TOUCHDOWN,CESSNA,CE-172,...,0.0,LYCOMI,O&VO-360 SER,360,1.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,2200.0,15.0,106.0,NaN
99994,20151216019599I,16-Dec-15,KALAMAZOO,MI,KALAMAZOO/BATTLE CREEK INTL,INCIDENT,SUBSTANTIAL,LANDING: TOUCHDOWN,BEECH,BE-36,...,0.0,CONT M,IO-550 SERIES,NaN,1.0,NaN,NaN,NaN,NaN,NaN
99995,20151217022219I,17-Dec-15,VENICE,FL,VENICE MUNI,INCIDENT,MINOR,LANDING: ROLLOUT,PARKS,NaN,...,0.0,AMA/EX,UNKNOWN ENG,NaN,NaN,AIRLINE TRANSPORT,16650.0,NaN,NaN,NaN
99996,20151217023139I,17-Dec-15,PHOENIX,AZ,PHOENIX SKY HARBOR INTL,INCIDENT,MINOR,TAKEOFF: CLIMB OUT,RAYTHEON,RA-390,...,0.0,WILLIA,FJ44-2A,TURBOF,2.0,AIRLINE TRANSPORT PILOT FLIGHT INSTRUCTOR,NaN,230.0,NaN,NaN
99997,20151218021509I,18-Dec-15,NaN,NaN,CAMARILLO,INCIDENT,MINOR,LANDING: APPROACH,CESSNA,CITATION 550 II,...,0.0,P&W CA,PW530A,NaN,2.0,UNKNOWN/FOREIGN,5500.0,150.0,NaN,NaN
99998,20151218021729I,18-Dec-15,BELLEVILLE,MI,WILLOW RUN,INCIDENT,MINOR,MANEUVER,CESSNA,CE-172,...,0.0,LYCOMI,O&VO-360 SER,NaN,1.0,PRIVATE PILOT,267.0,44.0,20.0,NaN
99999,20151218024079I,18-Dec-15,LEAVENWORTH,KS,SHERMAN AAF,INCIDENT,MINOR,LANDING: TOUCHDOWN,PIPER,PA-28,...,0.0,LYCOMI,O&VO-360 SER,NaN,NaN,STUDENT,18.0,13.0,13.0,NaN

In [2]:
df2 = pd.read_csv('PEP_2017_PEPCUMCHG.ST05_with_ann_sorted_small.csv')
# A manually edited excel file representing the census population data is used
# irrelevant columns were removed
df2

,Id2,Geography,"Population Estimate - April 1, 2010 Estimates Base","Population Estimate - July 1, 2017"
0,1,Alabama,4780135,4874747
1,2,Alaska,710249,739795
2,4,Arizona,6392309,7016270
3,5,Arkansas,2916031,3004279
4,6,California,37254518,39536653
5,8,Colorado,5029325,5607154
6,9,Connecticut,3574114,3588184
7,10,Delaware,897936,961939
8,11,District of Columbia,601766,693972
9,12,Florida,18804594,20984400
10,13,Georgia,9688690,10429379
11,15,Hawaii,1360301,1427538
12,16,Idaho,1567650,1716943
13,17,Illinois,12831565,12802023
14,18,Indiana,6484125,6666818
15,19,Iowa,3046869,3145711
16,20,Kansas,2853130,2913123
17,21,Kentucky,4339340,4454189
18,22,Louisiana,4533478,4684333
19,23,Maine,1328362,1335907
20,24,Maryland,5773807,6052177
21,25,Massachusetts,6547808,6859819
22,26,Michigan,9884129,9962311
23,27,Minnesota,5303924,5576606
24,28,Mississippi,2968103,2984100
25,29,Missouri,5988925,6113532
26,30,Montana,989414,1050493
27,31,Nebraska,1826327,1920076
28,32,Nevada,2700691,2998039
29,33,New Hampshire,1316460,1342795
30,34,New Jersey,8791953,9005644
31,35,New Mexico,2059207,2088070
32,36,New York,19378110,19849399
33,37,North Carolina,9535721,10273419
34,38,North Dakota,672585,755393
35,39,Ohio,11536730,11658609
36,40,Oklahoma,3751598,3930864
37,41,Oregon,3831072,4142776
38,42,Pennsylvania,12702857,12805537
39,44,Rhode Island,1052945,1059639
40,45,South Carolina,4625381,5024369
41,46,South Dakota,814197,869666
42,47,Tennessee,6346295,6715984
43,48,Texas,25146100,28304596
44,49,Utah,2763889,3101833
45,50,Vermont,625741,623657
46,51,Virginia,8001043,8470020
47,53,Washington,6724545,7405743
48,54,West Virginia,1853006,1815857
49,55,Wisconsin,5687288,5795483
50,56,Wyoming,563767,579315
51,72,Puerto Rico,3726157,3337177

In [3]:
# Dropping District of Columbia and Puerto Rico
df2.drop(8,axis=0,inplace=True)
df2.drop(51,axis=0,inplace=True)
df2

,Id2,Geography,"Population Estimate - April 1, 2010 Estimates Base","Population Estimate - July 1, 2017"
0,1,Alabama,4780135,4874747
1,2,Alaska,710249,739795
2,4,Arizona,6392309,7016270
3,5,Arkansas,2916031,3004279
4,6,California,37254518,39536653
5,8,Colorado,5029325,5607154
6,9,Connecticut,3574114,3588184
7,10,Delaware,897936,961939
9,12,Florida,18804594,20984400
10,13,Georgia,9688690,10429379
11,15,Hawaii,1360301,1427538
12,16,Idaho,1567650,1716943
13,17,Illinois,12831565,12802023
14,18,Indiana,6484125,6666818
15,19,Iowa,3046869,3145711
16,20,Kansas,2853130,2913123
17,21,Kentucky,4339340,4454189
18,22,Louisiana,4533478,4684333
19,23,Maine,1328362,1335907
20,24,Maryland,5773807,6052177
21,25,Massachusetts,6547808,6859819
22,26,Michigan,9884129,9962311
23,27,Minnesota,5303924,5576606
24,28,Mississippi,2968103,2984100
25,29,Missouri,5988925,6113532
26,30,Montana,989414,1050493
27,31,Nebraska,1826327,1920076
28,32,Nevada,2700691,2998039
29,33,New Hampshire,1316460,1342795
30,34,New Jersey,8791953,9005644
31,35,New Mexico,2059207,2088070
32,36,New York,19378110,19849399
33,37,North Carolina,9535721,10273419
34,38,North Dakota,672585,755393
35,39,Ohio,11536730,11658609
36,40,Oklahoma,3751598,3930864
37,41,Oregon,3831072,4142776
38,42,Pennsylvania,12702857,12805537
39,44,Rhode Island,1052945,1059639
40,45,South Carolina,4625381,5024369
41,46,South Dakota,814197,869666
42,47,Tennessee,6346295,6715984
43,48,Texas,25146100,28304596
44,49,Utah,2763889,3101833
45,50,Vermont,625741,623657
46,51,Virginia,8001043,8470020
47,53,Washington,6724545,7405743
48,54,West Virginia,1853006,1815857
49,55,Wisconsin,5687288,5795483
50,56,Wyoming,563767,579315

In [4]:
# Making sure there are 50 states remaining
len(df2['Geography'].value_counts())

50

In [5]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

In [16]:
# Create a dataframe that has each US state and their corresponding abbreviations 
df3 = pd.DataFrame.from_dict(us_state_abbrev, orient='index')
df3

                 0
Alabama         AL
Alaska          AK
Arizona         AZ
Arkansas        AR
California      CA
Colorado        CO
Connecticut     CT
Delaware        DE
Florida         FL
Georgia         GA
Hawaii          HI
Idaho           ID
Illinois        IL
Indiana         IN
Iowa            IA
Kansas          KS
Kentucky        KY
Louisiana       LA
Maine           ME
Maryland        MD
Massachusetts   MA
Michigan        MI
Minnesota       MN
Mississippi     MS
Missouri        MO
Montana         MT
Nebraska        NE
Nevada          NV
New Hampshire   NH
New Jersey      NJ
New Mexico      NM
New York        NY
North Carolina  NC
North Dakota    ND
Ohio            OH
Oklahoma        OK
Oregon          OR
Pennsylvania    PA
Rhode Island    RI
South Carolina  SC
South Dakota    SD
Tennessee       TN
Texas           TX
Utah            UT
Vermont         VT
Virginia        VA
Washington      WA
West Virginia   WV
Wisconsin       WI
Wyoming         WY

In [17]:
# Join the abreviation dataframe and the census population data
df2_abrv = df2.join(df3, on='Geography')
df2_abrv

,Id2,Geography,"Population Estimate - April 1, 2010 Estimates Base","Population Estimate - July 1, 2017",0
0,1,Alabama,4780135,4874747,AL
1,2,Alaska,710249,739795,AK
2,4,Arizona,6392309,7016270,AZ
3,5,Arkansas,2916031,3004279,AR
4,6,California,37254518,39536653,CA
5,8,Colorado,5029325,5607154,CO
6,9,Connecticut,3574114,3588184,CT
7,10,Delaware,897936,961939,DE
9,12,Florida,18804594,20984400,FL
10,13,Georgia,9688690,10429379,GA
11,15,Hawaii,1360301,1427538,HI
12,16,Idaho,1567650,1716943,ID
13,17,Illinois,12831565,12802023,IL
14,18,Indiana,6484125,6666818,IN
15,19,Iowa,3046869,3145711,IA
16,20,Kansas,2853130,2913123,KS
17,21,Kentucky,4339340,4454189,KY
18,22,Louisiana,4533478,4684333,LA
19,23,Maine,1328362,1335907,ME
20,24,Maryland,5773807,6052177,MD
21,25,Massachusetts,6547808,6859819,MA
22,26,Michigan,9884129,9962311,MI
23,27,Minnesota,5303924,5576606,MN
24,28,Mississippi,2968103,2984100,MS
25,29,Missouri,5988925,6113532,MO
26,30,Montana,989414,1050493,MT
27,31,Nebraska,1826327,1920076,NE
28,32,Nevada,2700691,2998039,NV
29,33,New Hampshire,1316460,1342795,NH
30,34,New Jersey,8791953,9005644,NJ
31,35,New Mexico,2059207,2088070,NM
32,36,New York,19378110,19849399,NY
33,37,North Carolina,9535721,10273419,NC
34,38,North Dakota,672585,755393,ND
35,39,Ohio,11536730,11658609,OH
36,40,Oklahoma,3751598,3930864,OK
37,41,Oregon,3831072,4142776,OR
38,42,Pennsylvania,12702857,12805537,PA
39,44,Rhode Island,1052945,1059639,RI
40,45,South Carolina,4625381,5024369,SC
41,46,South Dakota,814197,869666,SD
42,47,Tennessee,6346295,6715984,TN
43,48,Texas,25146100,28304596,TX
44,49,Utah,2763889,3101833,UT
45,50,Vermont,625741,623657,VT
46,51,Virginia,8001043,8470020,VA
47,53,Washington,6724545,7405743,WA
48,54,West Virginia,1853006,1815857,WV
49,55,Wisconsin,5687288,5795483,WI
50,56,Wyoming,563767,579315,WY

In [18]:
# Now have a df containing the state abreviations and the population estimates
state_abrv = df2_abrv[0]
df2_abrv['state_abrv'] = state_abrv

population = df2_abrv['Population Estimate - July 1, 2017']
df2_abrv['population_estimate'] = population
df2_abrv

,Id2,Geography,"Population Estimate - April 1, 2010 Estimates Base","Population Estimate - July 1, 2017",0,state_abrv,population_estimate
0,1,Alabama,4780135,4874747,AL,AL,4874747
1,2,Alaska,710249,739795,AK,AK,739795
2,4,Arizona,6392309,7016270,AZ,AZ,7016270
3,5,Arkansas,2916031,3004279,AR,AR,3004279
4,6,California,37254518,39536653,CA,CA,39536653
5,8,Colorado,5029325,5607154,CO,CO,5607154
6,9,Connecticut,3574114,3588184,CT,CT,3588184
7,10,Delaware,897936,961939,DE,DE,961939
9,12,Florida,18804594,20984400,FL,FL,20984400
10,13,Georgia,9688690,10429379,GA,GA,10429379
11,15,Hawaii,1360301,1427538,HI,HI,1427538
12,16,Idaho,1567650,1716943,ID,ID,1716943
13,17,Illinois,12831565,12802023,IL,IL,12802023
14,18,Indiana,6484125,6666818,IN,IN,6666818
15,19,Iowa,3046869,3145711,IA,IA,3145711
16,20,Kansas,2853130,2913123,KS,KS,2913123
17,21,Kentucky,4339340,4454189,KY,KY,4454189
18,22,Louisiana,4533478,4684333,LA,LA,4684333
19,23,Maine,1328362,1335907,ME,ME,1335907
20,24,Maryland,5773807,6052177,MD,MD,6052177
21,25,Massachusetts,6547808,6859819,MA,MA,6859819
22,26,Michigan,9884129,9962311,MI,MI,9962311
23,27,Minnesota,5303924,5576606,MN,MN,5576606
24,28,Mississippi,2968103,2984100,MS,MS,2984100
25,29,Missouri,5988925,6113532,MO,MO,6113532
26,30,Montana,989414,1050493,MT,MT,1050493
27,31,Nebraska,1826327,1920076,NE,NE,1920076
28,32,Nevada,2700691,2998039,NV,NV,2998039
29,33,New Hampshire,1316460,1342795,NH,NH,1342795
30,34,New Jersey,8791953,9005644,NJ,NJ,9005644
31,35,New Mexico,2059207,2088070,NM,NM,2088070
32,36,New York,19378110,19849399,NY,NY,19849399
33,37,North Carolina,9535721,10273419,NC,NC,10273419
34,38,North Dakota,672585,755393,ND,ND,755393
35,39,Ohio,11536730,11658609,OH,OH,11658609
36,40,Oklahoma,3751598,3930864,OK,OK,3930864
37,41,Oregon,3831072,4142776,OR,OR,4142776
38,42,Pennsylvania,12702857,12805537,PA,PA,12805537
39,44,Rhode Island,1052945,1059639,RI,RI,1059639
40,45,South Carolina,4625381,5024369,SC,SC,5024369
41,46,South Dakota,814197,869666,SD,SD,869666
42,47,Tennessee,6346295,6715984,TN,TN,6715984
43,48,Texas,25146100,28304596,TX,TX,28304596
44,49,Utah,2763889,3101833,UT,UT,3101833
45,50,Vermont,625741,623657,VT,VT,623657
46,51,Virginia,8001043,8470020,VA,VA,8470020
47,53,Washington,6724545,7405743,WA,WA,7405743
48,54,West Virginia,1853006,1815857,WV,WV,1815857
49,55,Wisconsin,5687288,5795483,WI,WI,5795483
50,56,Wyoming,563767,579315,WY,WY,579315

In [19]:
# drop the irrelevant 2010 estimate
df2_abrv.drop(['Id2', 'Population Estimate - April 1, 2010 Estimates Base', 'Population Estimate - July 1, 2017',0], axis=1, inplace=True)
#df2_abrv.drop(['Geography'], axis=1, inplace=True)
df2_abrv

         Geography state_abrv  population_estimate
0          Alabama         AL              4874747
1           Alaska         AK               739795
2          Arizona         AZ              7016270
3         Arkansas         AR              3004279
4       California         CA             39536653
5         Colorado         CO              5607154
6      Connecticut         CT              3588184
7         Delaware         DE               961939
9          Florida         FL             20984400
10         Georgia         GA             10429379
11          Hawaii         HI              1427538
12           Idaho         ID              1716943
13        Illinois         IL             12802023
14         Indiana         IN              6666818
15            Iowa         IA              3145711
16          Kansas         KS              2913123
17        Kentucky         KY              4454189
18       Louisiana         LA              4684333
19           Maine         ME              1335907
20        Maryland         MD              6052177
21   Massachusetts         MA              6859819
22        Michigan         MI              9962311
23       Minnesota         MN              5576606
24     Mississippi         MS              2984100
25        Missouri         MO              6113532
26         Montana         MT              1050493
27        Nebraska         NE              1920076
28          Nevada         NV              2998039
29   New Hampshire         NH              1342795
30      New Jersey         NJ              9005644
31      New Mexico         NM              2088070
32        New York         NY             19849399
33  North Carolina         NC             10273419
34    North Dakota         ND               755393
35            Ohio         OH             11658609
36        Oklahoma         OK              3930864
37          Oregon         OR              4142776
38    Pennsylvania         PA             12805537
39    Rhode Island         RI              1059639
40  South Carolina         SC              5024369
41    South Dakota         SD               869666
42       Tennessee         TN              6715984
43           Texas         TX             28304596
44            Utah         UT              3101833
45         Vermont         VT               623657
46        Virginia         VA              8470020
47      Washington         WA              7405743
48   West Virginia         WV              1815857
49       Wisconsin         WI              5795483
50         Wyoming         WY               579315

In [20]:
# We now have a final dataframe that can be used for the state normalization
df_final = df.merge(df2_abrv, left_on='Event State',  right_on='state_abrv')
df_final

,AIDS Report Number,Local Event Date,Event City,Event State,Event Airport,Event Type,Aircraft Damage,Flight Phase,Aircraft Make,Aircraft Model,...,Engine Group Code,Nbr of Engines,PIC Certificate Type,PIC Flight Time Total Hrs,PIC Flight Time Total Make-Model,,.1,Geography,state_abrv,population_estimate
0,19780101000019I,1-Jan-78,WAHPETON,ND,BRECKENRIDGE,INCIDENT,MINOR,ROLL-OUT (FIXED WING),CESSNA,CE-182,...,NaN,1.0,PRIVATE PILOT,245.0,136.0,0.0,0.0,North Dakota,ND,755393
1,19780102000359I,2-Jan-78,LANGDON,ND,LANGDON MUNI,INCIDENT,MINOR,TOUCH AND GO LANDING,GULSTM,GA-AA,...,NaN,1.0,STUDENT,29.0,21.0,0.0,0.0,North Dakota,ND,755393
2,19780102000519I,2-Jan-78,MINOT,ND,NaN,INCIDENT,NaN,FCD/PREC LDG FROM CRUISE,CESSNA,CE-150,...,O200,1.0,PRIVATE PILOT,600.0,100.0,0.0,0.0,North Dakota,ND,755393
3,19780113002859I,13-Jan-78,BEULAH,ND,BUELAH MUNI,INCIDENT,MINOR,TO ABORTED (FIXED WING),CESSNA,CE-310,...,NaN,2.0,COMMERCIAL PILOT,4100.0,650.0,0.0,0.0,North Dakota,ND,755393
4,19780121003979I,21-Jan-78,NEWBURY,ND,NaN,INCIDENT,MINOR,ROLL-OUT (FIXED WING),GULSTM,GA-AA,...,NaN,1.0,PRIVATE PILOT,658.0,45.0,0.0,0.0,North Dakota,ND,755393
5,19780210006759I,10-Feb-78,FARGO,ND,HECTOR INTL,INCIDENT,NaN,ROLL-OUT (FIXED WING),BEECH,BE-35,...,NaN,1.0,COMMERCIAL PILOT,1500.0,0.0,0.0,0.0,North Dakota,ND,755393
6,19780215006659I,15-Feb-78,FARGO,ND,HECTOR INTL,INCIDENT,MINOR,IN TRAFFIC PATTERN-CIRCLING,CESSNA,CE-177,...,NaN,1.0,COMMERCIAL PILOT,190.0,18.0,0.0,0.0,North Dakota,ND,755393
7,19780309015579I,9-Mar-78,NORTHWOOD,ND,NORTHWOOD MUNI-VINCE FIELD,INCIDENT,MINOR,ROLL-OUT (FIXED WING),BEECH,BE-23,...,NaN,1.0,PRIVATE PILOT,291.0,27.0,0.0,0.0,North Dakota,ND,755393
8,19780402008309I,2-Apr-78,GRAND FORKS,ND,NaN,INCIDENT,MINOR,FCD/PREC LDG FROM CRUISE,BELL,BHT-206,...,250C,1.0,COMMERCIAL PILOT,4101.0,2486.0,0.0,0.0,North Dakota,ND,755393
9,19780618046589I,18-Jun-78,FARGO,ND,HECTOR INTL,INCIDENT,MINOR,OPERATIONS ON GROUND FROM LANDING/ROTORCRAFT,PIPER,PA-28,...,NaN,1.0,COMMERCIAL PILOT,265.0,60.0,0.0,0.0,North Dakota,ND,755393
10,19780622047129I,22-Jun-78,LANGDON,ND,NaN,INCIDENT,MINOR,LOW LEVEL OPERATIONS,PIPER,PA-25,...,NaN,1.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,2695.0,80.0,0.0,0.0,North Dakota,ND,755393
11,19780622047189I,22-Jun-78,WATFORD CITY,ND,NaN,INCIDENT,MINOR,FCD/PREC LDG FROM CRUISE,PIPER,PA-25,...,NaN,1.0,COMMERCIAL PILOT,6000.0,2700.0,0.0,0.0,North Dakota,ND,755393
12,19780629034139I,29-Jun-78,VALLEY CITY,ND,VALLEY CITY MUNI,INCIDENT,MINOR,ROLL-OUT (FIXED WING),BEECH,BE-35,...,NaN,1.0,AIRLINE TRANSPORT PILOT FLIGHT INSTRUCTOR,4000.0,1100.0,0.0,0.0,North Dakota,ND,755393
13,19780711043209I,11-Jul-78,DICKINSON,ND,DICKINSON MUNI,INCIDENT,NaN,TO ABORTED (FIXED WING),BEECH,BE-18,...,NaN,2.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,2800.0,150.0,0.0,0.0,North Dakota,ND,755393
14,19780720035719I,20-Jul-78,FARGO,ND,HECTOR INTL,INCIDENT,MINOR,ROLL-OUT (FIXED WING),BEECH,BE-58,...,NaN,2.0,COMMERCIAL PILOT,5943.0,525.0,0.0,0.0,North Dakota,ND,755393
15,19780722038629I,22-Jul-78,MINOT,ND,MINOT INTL,INCIDENT,MINOR,"GROUND TAXI, OTHER AIRPLANE",CESSNA,CE-305,...,NaN,1.0,COMMERCIAL PILOT,450.0,100.0,0.0,0.0,North Dakota,ND,755393
16,19780807050459I,7-Aug-78,BISMARCK,ND,BISMARCK MUNI,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-210,...,NaN,1.0,PRIVATE PILOT,NaN,0.0,0.0,0.0,North Dakota,ND,755393
17,19780823048049I,23-Aug-78,WILLISTON,ND,WILLISTON MUNI,INCIDENT,NaN,FCD/PREC LDG FROM CRUISE,CESSNA,CE-182,...,NaN,1.0,COMMERCIAL PILOT,3500.0,800.0,0.0,0.0,North Dakota,ND,755393
18,19780901016769I,1-Sep-78,FARGO,ND,HECTOR INTL,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-172,...,NaN,1.0,STUDENT,21.0,21.0,0.0,0.0,North Dakota,ND,755393
19,19780913017389I,13-Sep-78,FARGO,ND,HECTOR INTL,INCIDENT,MINOR,ROLL-OUT (FIXED WING),BEECH,BE-58,...,NaN,2.0,COMMERCIAL PILOT,1580.0,300.0,0.0,0.0,North Dakota,ND,755393
20,19780917019399I,17-Sep-78,COOPERSTOWN,ND,COOPERSTOWN MUNI,INCIDENT,MINOR,OTHER GROUND OPERATIONS,BREEZY,BREEZY,...,NaN,1.0,COMMERCIAL PILOT,750.0,25.0,0.0,0.0,North Dakota,ND,755393
21,19780926028639I,26-Sep-78,GRAND FORKS,ND,GRAND FORKS MUNI,INCIDENT,NaN,LEVEL OFF TOUCHDOWN,CESSNA,CE-414,...,NaN,2.0,COMMERCIAL PILOT,900.0,250.0,0.0,0.0,North Dakota,ND,755393
22,19781011030089I,11-Oct-78,GRAND FORKS,ND,GRAND FORKS INTL,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-150,...,NaN,1.0,STUDENT,15.0,15.0,0.0,0.0,North Dakota,ND,755393
23,19781104023909I,4-Nov-78,LEONARD,ND,NaN,INCIDENT,MINOR,FINAL APPROACH,CESSNA,CE-152,...,NaN,1.0,COMMERCIAL PILOT,NaN,0.0,0.0,0.0,North Dakota,ND,755393
24,19781107023089I,7-Nov-78,DICKINSON,ND,DICKINSON MUNI,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,BEECH,BE-100,...,NaN,2.0,COMMERCIAL PILOT,28380.0,300.0,0.0,0.0,North Dakota,ND,755393
25,19781124025589I,24-Nov-78,GRAND FORKS,ND,GRAND FORKS MUNI,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,BEECH,BE-23,...,NaN,1.0,COMMERCIAL PILOT,280.0,34.0,0.0,0.0,North Dakota,ND,755393
26,19790105000569I,5-Jan-79,ROLLA,ND,ROLLA MUNI,INCIDENT,MINOR,ROLL-OUT (FIXED WING),STNSON,SR-108,...,NaN,1.0,PRIVATE PILOT,258.0,39.0,0.0,0.0,North Dakota,ND,755393
27,19790208005529I,8-Feb-79,BISMARCK,ND,HARVEY MUNI,INCIDENT,MINOR,ROLL-OUT (FIXED WING),CESSNA,CE-172,...,NaN,1.0,COMMERCIAL PILOT,2034.0,663.0,0.0,0.0,North Dakota,ND,755393
28,19790228008589I,28-Feb-79,DICKINSON,ND,DICKINSON MUNI,INCIDENT,MINOR,ROLL-OUT (FIXED WING),CESSNA,CE-152,...,NaN,1.0,STUDENT,29.0,29.0,0.0,0.0,North Dakota,ND,755393
29,19790304010079I,4-Mar-79,MINOT,ND,MINOT INTL,INCIDENT,MINOR,"AERIAL TAXI, OTHER HELICOPTER",HILLER,HILLER-OH23,...,NaN,1.0,COMMERCIAL PILOT,5350.0,350.0,0.0,0.0,North Dakota,ND,755393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98229,20010214002809I,14-Feb-01,GEORGETOWN,DE,SUSSEX COUNTY,INCIDENT,MINOR,ROLL-OUT (FIXED WING),BEECH,BE-35,...,O550,1.0,PRIVATE PILOT,NaN,300.0,65.0,NaN,Delaware,DE,961939
98230,20010430014879I,30-Apr-01,NaN,DE,NaN,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,BEECH,BE-35,...,O520,1.0,COMMERCIAL PILOT,3300.0,2000.0,15.0,NaN,Delaware,DE,961939
98231,20010610013709I,10-Jun-01,LAUREL,DE,LAUREL,INCIDENT,NaN,NORMAL CRUISE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delaware,DE,961939
98232,20011229033859I,29-Dec-01,DOVER,DE,NaN,INCIDENT,MINOR,NORMAL CRUISE,ENSTRM,ENSTRM-F28,...,NaN,1.0,PRIVATE PILOT,808.0,61.0,21.0,NaN,Delaware,DE,961939
98233,20020516019469I,16-May-02,ROXANA,DE,WEST PVT,INCIDENT,MINOR,TO ABORTED (FIXED WING),MOONEY,M-20,...,O360,1.0,PRIVATE PILOT,3060.0,3060.0,10.0,NaN,Delaware,DE,961939
98234,20020612019089I,12-Jun-02,LAUREL,DE,NaN,INCIDENT,MINOR,LOW LEVEL OPERATIONS,PIPER,PA-25,...,O540,1.0,COMMERCIAL PILOT,800.0,350.0,100.0,NaN,Delaware,DE,961939
98235,20030405017139I,5-Apr-03,LAUREL,DE,LAUREL,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-172,...,O360,1.0,PRIVATE PILOT,231.0,157.0,56.0,NaN,Delaware,DE,961939
98236,20040622022189I,22-Jun-04,GEORGETOWN,DE,SUSSEX COUNTY,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,YAKOVLEV,YAK-52,...,NaN,1.0,COMMERCIAL PILOT,2435.0,9.0,67.0,NaN,Delaware,DE,961939
98237,20050808025479I,8-Aug-05,DOVER,DE,DELAWARE AIRPARK,INCIDENT,SUBSTANTIAL,STARTING ENGINES,PIPER,PA-24,...,NaN,1.0,PRIVATE PILOT,380.0,130.0,37.0,NaN,Delaware,DE,961939
98238,20051105033249I,5-Nov-05,LAUREL,DE,LAUREL,INCIDENT,NaN,NORMAL CRUISE,CESSNA,CE-172,...,NaN,1.0,PRIVATE PILOT,180.0,155.0,14.0,NaN,Delaware,DE,961939
98239,20060702023279I,2-Jul-06,DOVER,DE,DELAWARE AIRPARK,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CE-177,...,NaN,1.0,COMMERCIAL PILOT,2810.0,1000.0,6.0,NaN,Delaware,DE,961939
98240,20070416016949I,16-Apr-07,WILMINGTON,DE,NEW CASTLE,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,CESSNA,CITATION SOVEREIGN,...,PW306,2.0,AIRLINE TRANSPORT PILOT FLIGHT INSTRUCTOR,4500.0,150.0,75.0,NaN,Delaware,DE,961939
98241,20070718019209I,18-Jul-07,DOVER,DE,NaN,INCIDENT,NONE,NORMAL CRUISE,PIPER,PA-28,...,NaN,1.0,PRIVATE PILOT,0.0,0.0,0.0,NaN,Delaware,DE,961939
98242,20071130829679I,30-Nov-07,WILMINGTON,DE,NEW CASTLE,INCIDENT,MINOR,LEVEL OFF TOUCHDOWN,PIPER,PA-34,...,O360,2.0,PRIVATE PILOT,250.0,10.0,10.0,NaN,Delaware,DE,961939
98243,20080104010909I,4-Jan-08,CHESWOLD,DE,NaN,INCIDENT,MINOR,FINAL APPROACH,BEECH,BE-36,...,NaN,1.0,PILOT NOT CERTIFICATED,0.0,0.0,0.0,NaN,Delaware,DE,961939
98244,20090425005339I,25-Apr-09,WILMINGTON,DE,NEW CASTLE,INCIDENT,MINOR,LANDING,CESSNA,CE-210,...,O520,1.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,12000.0,79.0,225.0,NaN,Delaware,DE,961939
98245,20090711011179I,11-Jul-09,WILMINGTON,DE,NEW CASTLE,INCIDENT,MINOR,LANDING,PIPER,PA-23,...,O540,2.0,AIRLINE TRANSPORT,3238.0,1298.0,32.0,NaN,Delaware,DE,961939
98246,20090912025509I,12-Sep-09,NaN,DE,NaN,INCIDENT,MINOR,CRUISE-LEVEL FLIGHT,PIPER,PA-18,...,NaN,NaN,COMMERCIAL PILOT,2651.0,0.0,0.0,NaN,Delaware,DE,961939
98247,20100220027609I,20-Feb-10,MIDDLETOWN,DE,SUMMIT,INCIDENT,MINOR,TAXI,MOONEY,M-20,...,NaN,1.0,COMMERCIAL PILOT,1409.0,530.0,8.0,NaN,Delaware,DE,961939
98248,20120311003019I,11-Mar-12,NEW CASTLE,DE,NEW CASTLE,INCIDENT,MINOR,LANDING: ROLLOUT,AERONCA,AR-7,...,NaN,1.0,PRIVATE PILOT,579.0,48.0,18.0,NaN,Delaware,DE,961939
98249,20121117024759I,17-Nov-12,DOVER,DE,DELAWARE AIRPARK,INCIDENT,MINOR,LANDING: ROLLOUT,BEECH,BE-95,...,B1B,2.0,PRIVATE PILOT,210.0,110.0,10.0,NaN,Delaware,DE,961939
98250,20121130027269I,30-Nov-12,NaN,DE,NEW CASTLE,INCIDENT,MINOR,TAXI,CESSNA,CE-172,...,NaN,1.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,1200.0,800.0,100.0,NaN,Delaware,DE,961939
98251,20130605008679I,5-Jun-13,LEWES,DE,NaN,INCIDENT,MINOR,LANDING: TOUCHDOWN,AGUSTA,AGUSTA-A109,...,NaN,2.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,NaN,NaN,NaN,NaN,Delaware,DE,961939
98252,20130616009999I,16-Jun-13,LAUREL,DE,LAUREL,INCIDENT,NONE,UNKNOWN,DE HAVILLAND-BOMBARDIER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delaware,DE,961939
98253,20130812016959I,12-Aug-13,DOVER,DE,DOVER AFB,INCIDENT,MINOR,LANDING: APPROACH,CESSNA,CE-172,...,NaN,1.0,COMMERCIAL PILOT FLIGHT INSTRUCTOR,2383.0,95.0,142.0,NaN,Delaware,DE,961939
98254,20140129001059I,29-Jan-14,NEW CASTLE,DE,NEW CASTLE,INCIDENT,NONE,CLIMB,CANADAIR-BOMBARDIER,CHALLENGER,...,NaN,NaN,AIRLINE TRANSPORT,13000.0,4146.0,178.0,NaN,Delaware,DE,961939
98255,20140702010929I,2-Jul-14,LEWES,DE,NaN,INCIDENT,MINOR,CRUISE-LEVEL FLIGHT,CESSNA,CE-152,...,NaN,1.0,PRIVATE PILOT,2500.0,NaN,NaN,NaN,Delaware,DE,961939
98256,20140808012439I,8-Aug-14,CAMDEN WYOMING,DE,JENKINS,INCIDENT,MINOR,LANDING: TOUCHDOWN,PIPER,PA-28,...,J3A5D,NaN,PRIVATE PILOT,176.0,37.0,20.0,NaN,Delaware,DE,961939
98257,20150322003279I,22-Mar-15,NEW CASTLE,DE,NEW CASTLE,INCIDENT,MINOR,TAXI,AIRBUS,A319,...,NaN,NaN,AIRLINE TRANSPORT,6949.0,4055.0,130.0,NaN,Delaware,DE,961939
98258,20150615013469I,15-Jun-15,CHESWOLD,DE,DELAWARE AIRPARK,INCIDENT,MINOR,TAXI,PIPER,PA-34,...,KB,NaN,PRIVATE PILOT,4000.0,2000.0,15.0,NaN,Delaware,DE,961939

In [32]:
# if you want to remove the additional columns can do:
#df_final.drop(['Geography', 'state_abrv'], axis=1, inplace=True)

import geopandas
import plotly
import plotly.plotly as py
import plotly.figure_factory as ff

plotly.tools.set_credentials_file(username='kerin', api_key='g325tbti6wc1LMvJDfOG')

state_count = (df_final['Event State'].value_counts())
state_count = state_count.rename_axis('States').reset_index(name='Values')
state_count = state_count.merge(df2_abrv, left_on = 'States', right_on = 'state_abrv')
state_count['Normalized'] = (state_count['Values']/state_count['population_estimate'])*100000
state_count

scl = [[0.0, 'rgb(242,240,247)'],[0.2, 'rgb(218,218,235)'],[0.4, 'rgb(188,189,220)'],\
            [0.6, 'rgb(158,154,200)'],[0.8, 'rgb(117,107,177)'],[1.0, 'rgb(84,39,143)']]

data = [ dict(
        type='choropleth',
        colorscale = scl,
        autocolorscale = False,
        locations = state_count['States'],
        z = state_count['Normalized'],
        locationmode = 'USA-states',
        marker = dict(
            line = dict (
                color = 'rgb(255,255,255)',
                width = 2
            ) ),
        colorbar = dict(
            title = "Normalized Accident Rate")
        ) ]

layout = dict(
        title = 'Number of Accidents Per State With Respect to the Total Population',
        geo = dict(
            scope='usa',
            projection=dict( type='albers usa' ),
            showlakes = True,
            lakecolor = 'rgb(255, 255, 255)'),
             )
    

fig = dict( data=data, layout=layout )
py.iplot(fig)